"""Alter ID on Creation

Revision ID: 5812dc31abc1
Revises: 666de4975dbe
Create Date: 2024-08-02 00:26:04.838860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5812dc31abc1'
down_revision = '666de4975dbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
