"""Adding missing fields to Tasks

Revision ID: 666de4975dbe
Revises: 561f57edb322
Create Date: 2024-08-01 23:39:26.588071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666de4975dbe'
down_revision = '561f57edb322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=True))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('completed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_date')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
