"""Adding Task model and user m2o relationship

Revision ID: f77ab927f425
Revises: a435508a8d1b
Create Date: 2024-08-01 20:19:34.641271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77ab927f425'
down_revision = 'a435508a8d1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE taskstatus ADD VALUE 'CANCELLED'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
